Repository kookmin-sw/capstone-2024-31, pull requests merged in 2024-05, with the labels that each got.

#77 [backend/feat] 예치금 및 level, xp 삭제
  backend/src/main/java/km/cd/backend/user/User.java
  backend/src/main/java/km/cd/backend/user/dto/UserResponse.java
Labels: 🍃 백엔드, 💡 기능

#69 [backend/feat] 초대 링크 생성 및 참여 기능
  backend/build.gradle
  backend/src/main/java/km/cd/backend/challenge/controller/ChallengeController.java
  backend/src/main/java/km/cd/backend/challenge/domain/Challenge.java
  backend/src/main/java/km/cd/backend/challenge/domain/mapper/ChallengeMapper.java
  backend/src/main/java/km/cd/backend/challenge/dto/request/ChallengeCreateRequest.java
  backend/src/main/java/km/cd/backend/challenge/dto/request/ChallengeInviteCodeRequest.java
  backend/src/main/java/km/cd/backend/challenge/dto/response/ChallengeInformationResponse.java
  backend/src/main/java/km/cd/backend/challenge/dto/response/ChallengeInviteCodeResponse.java
  backend/src/main/java/km/cd/backend/challenge/dto/response/ChallengeStatusResponse.java
  backend/src/main/java/km/cd/backend/challenge/repository/ChallengeRepository.java
  backend/src/main/java/km/cd/backend/challenge/service/ChallengeService.java
  backend/src/main/java/km/cd/backend/common/config/RedisConfig.java
  backend/src/main/java/km/cd/backend/common/error/ExceptionCode.java
  backend/src/main/java/km/cd/backend/common/utils/RandomUtil.java
  backend/src/main/java/km/cd/backend/common/utils/redis/RedisUtil.java
  backend/src/main/java/km/cd/backend/common/utils/s3/S3Uploader.java
  backend/src/main/java/km/cd/backend/common/utils/sms/SmsController.java
  backend/src/main/java/km/cd/backend/common/utils/sms/SmsRequestDto.java
  backend/src/main/java/km/cd/backend/common/utils/sms/SmsUtil.java
  backend/src/main/java/km/cd/backend/community/service/PostService.java
  backend/src/main/resources/application.yml
  backend/src/test/java/km/cd/backend/challenge/ChallengeControllerTest.java
  backend/src/test/java/km/cd/backend/challenge/ChallengeFixture.java
  backend/src/test/java/km/cd/backend/challenge/ChallengeServiceTest.java
  backend/src/test/java/km/cd/backend/challenge/UserFixture.java
  backend/src/test/java/km/cd/backend/helper/ApiTestHelper.java
  backend/src/test/java/km/cd/backend/helper/IntegrationTest.java
Labels: 중요도-하, 🍃 백엔드, 💡 기능

#78 [BE/feat] 챌린지 response 필드 수정 및 participant api 개발
  backend/src/main/java/km/cd/backend/challenge/controller/ChallengeController.java
  backend/src/main/java/km/cd/backend/challenge/domain/Participant.java
  backend/src/main/java/km/cd/backend/challenge/domain/mapper/ChallengeMapper.java
  backend/src/main/java/km/cd/backend/challenge/dto/request/ChallengeCreateRequest.java
  backend/src/main/java/km/cd/backend/challenge/dto/response/ChallengeInformationResponse.java
  backend/src/main/java/km/cd/backend/challenge/dto/response/ChallengeInviteCodeResponse.java
  backend/src/main/java/km/cd/backend/challenge/dto/response/ParticipantResponse.java
  backend/src/main/java/km/cd/backend/challenge/service/ChallengeService.java
  backend/src/main/java/km/cd/backend/common/error/ExceptionCode.java
  backend/src/main/java/km/cd/backend/common/utils/redis/RedisUtil.java
  backend/src/test/java/km/cd/backend/challenge/ChallengeControllerTest.java
  backend/src/test/java/km/cd/backend/challenge/ChallengeServiceTest.java
  backend/src/test/java/km/cd/backend/challenge/fixture/ChallengeFixture.java
  backend/src/test/java/km/cd/backend/challenge/fixture/ChallengeRequestFixture.java
  backend/src/test/java/km/cd/backend/challenge/fixture/ChallengeResponseFixture.java
  backend/src/test/java/km/cd/backend/challenge/fixture/UserFixture.java
Labels: 중요도-하, 🍃 백엔드, 💡 기능

#81 [backend/feat] fcm 알림 기능
  .github/workflows/CICD.yml
  backend/.gitignore
  backend/build.gradle
  backend/src/main/java/km/cd/backend/fcm/controller/FcmController.java
  backend/src/main/java/km/cd/backend/fcm/dto/FcmRequest.java
  backend/src/main/java/km/cd/backend/fcm/dto/FcmResponse.java
  backend/src/main/java/km/cd/backend/fcm/service/FcmService.java
Labels: 중요도-하, 🍃 백엔드, 💡 기능

#86 [FE/fix] 유저 정보 받아오기 오류 수정
  frontend/lib/challenge/certification/camera/camera_app.dart
  frontend/lib/main.dart
  frontend/lib/model/controller/user_controller.dart
  frontend/lib/model/data/user.dart
  frontend/pubspec.lock
Labels: 중요도-상, 💻 프론트엔드, 🔨 리팩터링, 🚨 버그

#89 [FE] 게시글 신고하기 기능 추가
  frontend/lib/challenge/create/create_challenge_screen_sec.dart
  frontend/lib/community/post_detail_screen.dart
  frontend/lib/community/post_report_bottomScreen.dart
  frontend/lib/community/widget/report_post_btn.dart
  frontend/pubspec.yaml
Labels: 중요도-중, 💻 프론트엔드, 💡 기능

#93 [frontend/feat] 챌린지 완료 페이지
  frontend/lib/challenge/complete/challenge_complete_screen.dart
  frontend/lib/challenge/complete/widget/cerification_post_card.dart
  frontend/lib/challenge/complete/widget/reward_card.dart
  frontend/lib/challenge/create/create_challenge_screen_sec.dart
  frontend/lib/challenge/detail/detail_challenge_screen.dart
  frontend/lib/challenge/detail/detail_imageDetail_screen.dart
  frontend/lib/challenge/detail/widgets/build_image_container.dart
  frontend/lib/challenge/detail/widgets/certification_method_widget.dart
  frontend/lib/challenge/detail/widgets/detail_widget_imformation.dart
  frontend/lib/challenge/detail/widgets/detail_widget_information.dart
  frontend/lib/challenge/detail/widgets/detail_widget_photoes.dart
  frontend/lib/community/post_card.dart
  frontend/lib/community/post_detail_screen.dart
  frontend/lib/community/tab_community_screen.dart
  frontend/lib/community/widget/post_card.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_challenge_item_card.dart
  frontend/lib/main/bottom_tabs/myRoutineUp/myRoutineUp_screen.dart
  frontend/lib/main/bottom_tabs/myRoutineUp/widget/myroutineWidget.dart
  frontend/lib/main/bottom_tabs/myRoutineUp/widget/myroutineup_card.dart
  frontend/lib/main/bottom_tabs/myRoutineUp/widget/progress_widget.dart
  frontend/lib/model/data/post.dart
  frontend/lib/model/data/sms.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: 중요도-중, 💻 프론트엔드, 💡 기능

#87 [backend/feature] 챌린지 필터링 및 페이징 검색 기능 구현
  backend/build.gradle
  backend/src/main/java/km/cd/backend/challenge/controller/ChallengeController.java
  backend/src/main/java/km/cd/backend/challenge/domain/Challenge.java
  backend/src/main/java/km/cd/backend/challenge/domain/ChallengeCategory.java
  backend/src/main/java/km/cd/backend/challenge/domain/mapper/ChallengeMapper.java
  backend/src/main/java/km/cd/backend/challenge/dto/request/ChallengeFilter.java
  backend/src/main/java/km/cd/backend/challenge/dto/response/ChallengeSimpleResponse.java
  backend/src/main/java/km/cd/backend/challenge/repository/ChallengeCustomRepository.java
  backend/src/main/java/km/cd/backend/challenge/repository/ChallengeCustomRepositoryImpl.java
  backend/src/main/java/km/cd/backend/challenge/repository/ChallengeRepository.java
  backend/src/main/java/km/cd/backend/challenge/service/ChallengeService.java
  backend/src/main/java/km/cd/backend/common/config/QuerydslConfig.java
  backend/src/test/java/km/cd/backend/challenge/ChallengeControllerTest.java
  backend/src/test/java/km/cd/backend/challenge/ChallengeServiceTest.java
  backend/src/test/java/km/cd/backend/challenge/fixture/ChallengeFixture.java
  backend/src/test/java/km/cd/backend/challenge/fixture/UserFixture.java
  backend/src/test/java/km/cd/backend/helper/ApiTestHelper.java
  backend/src/test/java/km/cd/backend/helper/IntegrationTest.java
Labels: 중요도-중, 🍃 백엔드, 💡 기능, 🤖 테스트

#103 [all/feat] 챌린지 생성 연동
  backend/src/main/java/km/cd/backend/challenge/controller/ChallengeController.java
  backend/src/main/java/km/cd/backend/challenge/domain/Challenge.java
  backend/src/main/java/km/cd/backend/challenge/domain/ChallengeCategory.java
  backend/src/main/java/km/cd/backend/challenge/domain/mapper/ChallengeMapper.java
  backend/src/main/java/km/cd/backend/challenge/dto/request/ChallengeCreateRequest.java
  backend/src/main/java/km/cd/backend/challenge/repository/ChallengeCustomRepositoryImpl.java
  backend/src/main/java/km/cd/backend/challenge/service/ChallengeService.java
  frontend/lib/challenge/certification/camera/camera_awosome.dart
  frontend/lib/challenge/create/create_challenge_screen_complete.dart
  frontend/lib/challenge/create/create_challenge_screen_fir.dart
  frontend/lib/challenge/create/create_challenge_screen_sec.dart
  frontend/lib/challenge/create/create_challenge_screen_thr.dart
  frontend/lib/challenge/create/widgets/create_body_part1.dart
  frontend/lib/challenge/create/widgets/create_body_part2.dart
  frontend/lib/challenge/create/widgets/create_body_part3.dart
  frontend/lib/challenge/join/join_challenge_screen_sec.dart
  frontend/lib/challenge/search/challenge_search_screen.dart
  frontend/lib/login/login_screen.dart
  frontend/lib/main.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_appBar.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_challenge_list.dart
  frontend/lib/main/bottom_tabs/home/home_screen.dart
  frontend/lib/main/main_screen.dart
  frontend/lib/model/controller/challenge_form_controller.dart
  frontend/lib/model/controller/user_controller.dart
  frontend/lib/model/data/challenge_form.dart
  frontend/lib/widgets/custom_button.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: 중요도-상, 🍃 백엔드, 💻 프론트엔드, 💡 기능

#105 [backend/feat] sms 인증 로직 구현 및 챌린지 참여 로직 수정
  backend/src/main/java/km/cd/backend/challenge/controller/ChallengeController.java
  backend/src/main/java/km/cd/backend/challenge/domain/Challenge.java
  backend/src/main/java/km/cd/backend/challenge/domain/Participant.java
  backend/src/main/java/km/cd/backend/challenge/domain/mapper/ChallengeMapper.java
  backend/src/main/java/km/cd/backend/challenge/domain/mapper/ParticipantMapper.java
  backend/src/main/java/km/cd/backend/challenge/dto/request/ChallengeCreateRequest.java
  backend/src/main/java/km/cd/backend/challenge/dto/request/ChallengeJoinRequest.java
  backend/src/main/java/km/cd/backend/challenge/dto/response/ChallengeInformationResponse.java
  backend/src/main/java/km/cd/backend/challenge/service/ChallengeService.java
  backend/src/main/java/km/cd/backend/common/config/MultipartJackson2HttpMessageConverter.java
  backend/src/main/java/km/cd/backend/common/error/ExceptionCode.java
  backend/src/main/java/km/cd/backend/common/utils/sms/ResultMessage.java
  backend/src/main/java/km/cd/backend/common/utils/sms/SmsCertificationDao.java
  backend/src/main/java/km/cd/backend/common/utils/sms/SmsCertificationRequest.java
  backend/src/main/java/km/cd/backend/common/utils/sms/SmsController.java
  backend/src/main/java/km/cd/backend/common/utils/sms/SmsResultRequest.java
  backend/src/main/java/km/cd/backend/common/utils/sms/SmsService.java
  backend/src/main/java/km/cd/backend/common/utils/sms/SmsUtil.java
  backend/src/test/java/km/cd/backend/challenge/ChallengeControllerTest.java
Labels: 중요도-하, 🍃 백엔드, 💡 기능

#109 [all/feature] 챌린지 검색 및 디테일 조회 기능 구현
  backend/src/main/java/km/cd/backend/challenge/controller/ChallengeController.java
  backend/src/main/java/km/cd/backend/challenge/domain/mapper/ChallengeMapper.java
  backend/src/main/java/km/cd/backend/challenge/dto/response/ChallengeSimpleResponse.java
  backend/src/main/java/km/cd/backend/challenge/repository/ChallengeCustomRepository.java
  backend/src/main/java/km/cd/backend/challenge/repository/ChallengeCustomRepositoryImpl.java
  backend/src/main/java/km/cd/backend/challenge/service/ChallengeService.java
  frontend/lib/challenge/complete/challenge_complete_screen.dart
  frontend/lib/challenge/create/create_challenge_screen_complete.dart
  frontend/lib/challenge/detail/detail_challenge_screen.dart
  frontend/lib/challenge/detail/detail_image_detail_screen.dart
  frontend/lib/challenge/detail/widgets/build_image_container.dart
  frontend/lib/challenge/detail/widgets/detail_widget_information.dart
  frontend/lib/challenge/detail/widgets/detail_widget_photoes.dart
  frontend/lib/challenge/join/join_challenge_screen.dart
  frontend/lib/challenge/search/challenge_search_screen.dart
  frontend/lib/challenge/state/state_challenge_screen.dart
  frontend/lib/main.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_challenge_item_card.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_challenge_list.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_challenge_state_box.dart
  frontend/lib/main/bottom_tabs/myRoutineUp/widget/myroutineWidget.dart
  frontend/lib/main/bottom_tabs/myRoutineUp/widget/myroutineup_card.dart
  frontend/lib/model/data/challenge.dart
  frontend/lib/model/data/challenge_category.dart
  frontend/lib/model/data/challenge_filter.dart
  frontend/lib/model/data/challenge_simple.dart
  frontend/lib/widgets/custom_button.dart
Labels: 중요도-상, 🍃 백엔드, 💻 프론트엔드, 💡 기능, 🤖 테스트

#113 [all/feat] 자신 챌린지 조회 및 화면에 띄우기
  backend/src/main/java/km/cd/backend/challenge/dto/enums/ChallengeFrequency.java
  backend/src/main/java/km/cd/backend/challenge/dto/response/ChallengeSimpleResponse.java
  backend/src/main/java/km/cd/backend/challenge/repository/ParticipantRepository.java
  backend/src/main/java/km/cd/backend/user/UserController.java
  backend/src/main/java/km/cd/backend/user/UserService.java
  frontend/lib/challenge/complete/challenge_complete_screen.dart
  frontend/lib/challenge/detail/detail_challenge_screen.dart
  frontend/lib/challenge/detail/widgets/certification_method_widget.dart
  frontend/lib/challenge/detail/widgets/detail_widget_information.dart
  frontend/lib/challenge/join/join_challenge_screen.dart
  frontend/lib/challenge/join/join_challenge_screen_sec.dart
  frontend/lib/challenge/search/challenge_search_screen.dart
  frontend/lib/challenge/state/state_challenge_screen.dart
  frontend/lib/main.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_category_component.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_challenge_item_card.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_challenge_list.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_challenge_recommend_box.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_challenge_state_box.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_top_stack_box.dart
  frontend/lib/main/bottom_tabs/home/home_screen.dart
  frontend/lib/main/bottom_tabs/myRoutineUp/Auth_screen.dart
  frontend/lib/main/bottom_tabs/myRoutineUp/myRoutineUp_screen.dart
  frontend/lib/main/bottom_tabs/myRoutineUp/my_routine_up_screen.dart
  frontend/lib/main/bottom_tabs/myRoutineUp/widget/my_routine_up_card.dart
  frontend/lib/main/bottom_tabs/myRoutineUp/widget/my_routine_widget.dart
  frontend/lib/main/bottom_tabs/myRoutineUp/widget/myroutineWidget.dart
  frontend/lib/main/bottom_tabs/myRoutineUp/widget/progress_widget.dart
  frontend/lib/main/main_screen.dart
  frontend/lib/model/controller/challenge_form_controller.dart
  frontend/lib/model/controller/user_controller.dart
  frontend/lib/model/data/challenge/challenge.dart
  frontend/lib/model/data/challenge/challenge_category.dart
  frontend/lib/model/data/challenge/challenge_filter.dart
  frontend/lib/model/data/challenge/challenge_form.dart
  frontend/lib/model/data/challenge/challenge_simple.dart
  frontend/lib/model/data/challenge/challenge_status.dart
  frontend/lib/model/data/user.dart
Labels: 중요도-상, 🍃 백엔드, 💻 프론트엔드, 💡 기능

#122 [be/feat] 백엔드 챌린지 보호 및 ChallengeSimpleResponse에 isPrivate 추가
  backend/src/main/java/km/cd/backend/challenge/controller/ChallengeController.java
  backend/src/main/java/km/cd/backend/challenge/dto/response/ChallengeSimpleResponse.java
  backend/src/main/java/km/cd/backend/challenge/service/ChallengeService.java
Labels: 🍃 백엔드, 💡 기능

#126 [backend/feat] 유저 정보에 프로필 이미지 추가 & follow list 조회 시 친구 이미지 첨부
  backend/src/main/java/km/cd/backend/challenge/dto/enums/FilePathEnum.java
  backend/src/main/java/km/cd/backend/challenge/service/ChallengeService.java
  backend/src/main/java/km/cd/backend/common/error/ExceptionCode.java
  backend/src/main/java/km/cd/backend/common/utils/s3/S3Uploader.java
  backend/src/main/java/km/cd/backend/user/UserController.java
  backend/src/main/java/km/cd/backend/user/UserService.java
  backend/src/main/java/km/cd/backend/user/domain/User.java
  backend/src/main/java/km/cd/backend/user/domain/mapper/FriendMapper.java
  backend/src/main/java/km/cd/backend/user/dto/FriendListResponse.java
  backend/src/main/java/km/cd/backend/user/dto/UserResponse.java
Labels: 중요도-하, 🍃 백엔드, 🔨 리팩터링

#127 [backend/feat] User 이미지 저장 필드 변경 및 카테고리 기능 구현
  backend/src/main/java/km/cd/backend/user/UserController.java
  backend/src/main/java/km/cd/backend/user/UserService.java
  backend/src/main/java/km/cd/backend/user/domain/User.java
  backend/src/main/java/km/cd/backend/user/domain/mapper/UserMapper.java
  backend/src/main/java/km/cd/backend/user/dto/UserCategoryRequest.java
  backend/src/main/java/km/cd/backend/user/dto/UserDetailResponse.java
  backend/src/main/java/km/cd/backend/user/dto/UserResponse.java
  backend/src/test/java/km/cd/backend/challenge/fixture/ChallengeFixture.java
Labels: 🍃 백엔드, 💡 기능, 🔨 리팩터링

#128 [backend/feat] 댓글 기능 수정
  backend/src/main/java/km/cd/backend/community/controller/PostController.java
  backend/src/main/java/km/cd/backend/community/dto/CommentResponse.java
  backend/src/main/java/km/cd/backend/community/mapper/CommentMapper.java
  backend/src/main/java/km/cd/backend/community/mapper/PostMapper.java
  backend/src/main/java/km/cd/backend/community/service/CommentService.java
Labels: 중요도-하, 🍃 백엔드, 🔨 리팩터링

#129 [backend/feat] 챌린지 진행 상태 필드 추가 및 Date -> LocalDate로 타입 변경
  backend/src/main/java/km/cd/backend/challenge/domain/Challenge.java
  backend/src/main/java/km/cd/backend/challenge/domain/mapper/ChallengeMapper.java
  backend/src/main/java/km/cd/backend/challenge/dto/enums/ChallengeStatus.java
  backend/src/main/java/km/cd/backend/challenge/dto/response/ChallengeInformationResponse.java
  backend/src/main/java/km/cd/backend/challenge/dto/response/ChallengeSimpleResponse.java
  backend/src/main/java/km/cd/backend/challenge/dto/response/ChallengeStatusResponse.java
  backend/src/main/java/km/cd/backend/challenge/repository/ChallengeRepository.java
  backend/src/main/java/km/cd/backend/challenge/scheduler/ChallengeFinishScheduler.java
  backend/src/main/java/km/cd/backend/challenge/service/ChallengeService.java
Labels: 🍃 백엔드, 💡 기능, 🔨 리팩터링

#130 [frontend/feature] 친구 팔로우 버튼 UI & 유저정보 연동
  .idea/libraries/Dart_Packages.xml
  frontend/lib/challenge/create/create_challenge_screen_thr.dart
  frontend/lib/challenge/join/join_challenge_screen.dart
  frontend/lib/community/create_posting_screen.dart
  frontend/lib/community/post_detail_screen.dart
  frontend/lib/community/tab_community_screen.dart
  frontend/lib/community/widget/follow_btn.dart
  frontend/lib/community/widget/post_card.dart
  frontend/lib/community/widget/post_top.dart
  frontend/lib/main.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_challenge_recommend_box.dart
  frontend/lib/main/bottom_tabs/myRoutineUp/widget/my_routine_up_card.dart
  frontend/lib/main/bottom_tabs/mypage/follow_point_screen/follower_tab.dart
  frontend/lib/main/bottom_tabs/mypage/mypage_pupleBtnBox.dart
  frontend/lib/main/bottom_tabs/mypage/widget/mypage_user_inform.dart
  frontend/lib/main/main_screen.dart
  frontend/lib/model/controller/user_controller.dart
  frontend/lib/model/data/freind.dart
  frontend/lib/model/data/user.dart
Labels: 중요도-상, 💻 프론트엔드, 💡 기능

#132 [backend/feat] 신고하기 기능 구현
  backend/src/main/java/km/cd/backend/common/error/ExceptionCode.java
  backend/src/main/java/km/cd/backend/community/controller/PostController.java
  backend/src/main/java/km/cd/backend/community/domain/Post.java
  backend/src/main/java/km/cd/backend/community/dto/ReportResponse.java
  backend/src/main/java/km/cd/backend/community/mapper/PostMapper.java
  backend/src/main/java/km/cd/backend/community/service/PostService.java
Labels: 중요도-하, 🍃 백엔드, 💡 기능

#133 [backend/feat] 깃허브 인증 추가
  backend/src/main/java/km/cd/backend/certification/controller/CertificationController.java
  backend/src/main/java/km/cd/backend/certification/domain/GitHubEvent.java
  backend/src/main/java/km/cd/backend/certification/dto/GithubCommitResponse.java
  backend/src/main/java/km/cd/backend/certification/service/CertificationService.java
  backend/src/main/java/km/cd/backend/user/UserController.java
  backend/src/main/java/km/cd/backend/user/UserService.java
  backend/src/main/java/km/cd/backend/user/domain/User.java
  backend/src/main/java/km/cd/backend/user/dto/GithubUsernameRequest.java
  backend/src/test/java/km/cd/backend/challenge/fixture/ChallengeFixture.java
Labels: 중요도-하, 🍃 백엔드, 💡 기능

#134 [backend/fix] get method는 requestBody를 지원하지 않아서 post 요청으로 변경
  backend/src/main/java/km/cd/backend/challenge/controller/ChallengeController.java
Labels: 중요도-하, 🍃 백엔드, 🚨 버그

#138 [All/feature] 비공개 챌린지 암호코드 확인 과정 구현
  frontend/lib/challenge/search/challenge_search_screen.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_challenge_list.dart
  frontend/lib/main/bottom_tabs/home/home_components/privateCode_input_dialog.dart
  frontend/lib/main/bottom_tabs/myRoutineUp/my_routine_up_screen.dart
  frontend/lib/main/main_screen.dart
  frontend/lib/model/data/challenge/challenge_filter.dart
Labels: 중요도-중, 🍃 백엔드, 💻 프론트엔드, 💡 기능

#141 [backend/feat] 유저 response 카테고리 필드 추가 및 챌린지 상태 에러 변경
  backend/src/main/java/km/cd/backend/challenge/service/ChallengeService.java
  backend/src/main/java/km/cd/backend/user/dto/UserResponse.java
Labels: 🍃 백엔드, 🔨 리팩터링, 🚨 버그

#145 [backend/feat] DataSeeder를 활용한 더미 데이터 생성 및 받아오는 API 개발
  backend/src/main/java/km/cd/backend/challenge/controller/ChallengeController.java
  backend/src/main/java/km/cd/backend/challenge/service/ChallengeService.java
  backend/src/main/java/km/cd/backend/common/utils/ChallengeDataSeeder.java
  frontend/lib/community/community_screen.dart
  frontend/lib/community/create_posting_screen.dart
  frontend/lib/model/data/createdPost.dart
  frontend/lib/model/data/post.dart
Labels: 중요도-하, 🍃 백엔드, 💡 기능

#146 [backend/feat] SMS 메시지 전송 에러 수정 & 챌린지 정보 API 추가 개발
  backend/src/main/java/km/cd/backend/challenge/controller/ChallengeController.java
  backend/src/main/java/km/cd/backend/challenge/service/ChallengeService.java
  backend/src/main/java/km/cd/backend/common/utils/sms/SmsController.java
  backend/src/main/java/km/cd/backend/common/utils/sms/SmsResultRequest.java
  backend/src/main/java/km/cd/backend/common/utils/sms/SmsService.java
  backend/src/main/java/km/cd/backend/common/utils/sms/SmsUtil.java
  backend/src/main/java/km/cd/backend/common/utils/sms/dto/SmsCertificationRequest.java
  backend/src/main/java/km/cd/backend/common/utils/sms/dto/SmsResultResponse.java
Labels: 🍃 백엔드, 💡 기능, 🔨 리팩터링, 🚨 버그

#147 [all] detail_screen null 에러 해결
  frontend/lib/challenge/detail/detail_challenge_screen.dart
  frontend/lib/challenge/join/join_challenge_screen.dart
  frontend/lib/challenge/join/join_challenge_screen_sec.dart
  frontend/lib/challenge/search/challenge_search_screen.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_category_component.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_challenge_item_card.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_challenge_recommend_box.dart
  frontend/lib/main/bottom_tabs/home/home_components/privateCode_input_dialog.dart
  frontend/lib/main/bottom_tabs/mypage/widget/category_bottom_sheet.dart
  frontend/lib/main/bottom_tabs/mypage/widget/mypage_user_inform.dart
  frontend/lib/model/config/category_card_list.dart
  frontend/lib/model/data/challenge/challenge_category.dart
Labels: 중요도-상, 💡 기능

#151 [FE/feat] 챌린지 바로 참가하기 기능추가
  backend/src/main/java/km/cd/backend/challenge/controller/ChallengeController.java
  backend/src/main/java/km/cd/backend/challenge/domain/Participant.java
  backend/src/main/java/km/cd/backend/challenge/service/ChallengeService.java
  backend/src/main/java/km/cd/backend/common/utils/sms/dto/SmsResultResponse.java
  frontend/lib/challenge/complete/challenge_complete_screen.dart
  frontend/lib/challenge/complete/widget/reward_card.dart
  frontend/lib/challenge/create/create_challenge_screen_complete.dart
  frontend/lib/challenge/create/create_challenge_screen_fir.dart
  frontend/lib/challenge/create/create_challenge_screen_sec.dart
  frontend/lib/challenge/create/create_challenge_screen_thr.dart
  frontend/lib/challenge/detail/detail_challenge_screen.dart
  frontend/lib/challenge/detail/detail_image_detail_screen.dart
  frontend/lib/challenge/detail/widgets/detail_widget_information.dart
  frontend/lib/challenge/join/join_challenge_screen.dart
  frontend/lib/challenge/join/join_challenge_screen_sec.dart
  frontend/lib/challenge/search/challenge_search_screen.dart
  frontend/lib/challenge/state/state_challenge_screen.dart
  frontend/lib/challenge/state/state_screen_widget.dart
  frontend/lib/community/community_screen.dart
  frontend/lib/community/post_detail_screen.dart
  frontend/lib/community/widget/post_card.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_appBar.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_category_component.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_challenge_item_card.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_challenge_list.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_challenge_state_box.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_top_ChalBox.dart
  frontend/lib/main/bottom_tabs/home/home_screen.dart
  frontend/lib/main/bottom_tabs/myRoutineUp/my_routine_up_screen.dart
  frontend/lib/main/bottom_tabs/myRoutineUp/widget/my_routine_up_card.dart
  frontend/lib/main/bottom_tabs/mypage/follow_point_screen/follower_tab.dart
  frontend/lib/main/bottom_tabs/mypage/follow_point_screen/following_tab.dart
  frontend/lib/main/bottom_tabs/mypage/follow_point_screen/point_screen.dart.dart
  frontend/lib/main/bottom_tabs/mypage/mypage_pupleBtnBox.dart
  frontend/lib/main/bottom_tabs/mypage/widget/categoryButtonPress.dart
  frontend/lib/main/bottom_tabs/mypage/widget/category_bottom_sheet.dart
  frontend/lib/main/bottom_tabs/mypage/widget/mypage_user_inform.dart
  frontend/lib/main/main_screen.dart
  frontend/lib/model/config/image_from_file.dart
  frontend/lib/model/config/palette.dart
  frontend/lib/model/controller/user_controller.dart
  frontend/lib/model/data/challenge/challenge.dart
  frontend/lib/model/data/challenge/challenge_join.dart
  frontend/lib/model/data/challenge/challenge_simple.dart
  frontend/lib/model/data/sms/sms.dart
  frontend/lib/model/data/sms/sms_certification.dart
  frontend/lib/model/data/sms/sms_result.dart
  frontend/lib/model/package/pie_chart/src/legend.dart
  frontend/lib/model/package/pie_chart/src/pie_chart.dart
  frontend/lib/widgets/custom_button.dart
  frontend/lib/widgets/rtu_button.dart
  frontend/lib/widgets/rtu_divider.dart
  frontend/pubspec.lock
  frontend/pubspec.yaml
Labels: 🍃 백엔드, 💻 프론트엔드, 💡 기능

#153 [all/feature] PostResponse 통일 및 like 넘겨주기
  .idea/libraries/Dart_Packages.xml
  backend/src/main/java/km/cd/backend/community/controller/PostController.java
  backend/src/main/java/km/cd/backend/community/dto/LikeResponse.java
  backend/src/main/java/km/cd/backend/community/dto/PostResponse.java
  backend/src/main/java/km/cd/backend/community/dto/PostSimpleResponse.java
  backend/src/main/java/km/cd/backend/community/mapper/PostMapper.java
  backend/src/main/java/km/cd/backend/community/service/PostService.java
  backend/src/test/java/km/cd/backend/community/service/PostServiceTest.java
  frontend/lib/community/CommunityService.dart
  frontend/lib/community/community_screen.dart
  frontend/lib/model/controller/user_controller.dart
  frontend/lib/model/data/post/post.dart
  frontend/lib/model/data/post/simple_post.dart
  frontend/lib/model/data/user.dart
  frontend/pubspec.lock
Labels: 🍃 백엔드, 💡 기능

#154 [all/feat] 좋아요 연동까지
  backend/src/main/java/km/cd/backend/challenge/domain/mapper/ChallengeMapper.java
  backend/src/main/java/km/cd/backend/challenge/dto/response/ChallengeInformationResponse.java
  backend/src/main/java/km/cd/backend/challenge/dto/response/ChallengeSimpleResponse.java
  backend/src/main/java/km/cd/backend/common/error/CustomException.java
  backend/src/main/java/km/cd/backend/common/error/ErrorResponse.java
  backend/src/main/java/km/cd/backend/community/controller/PostController.java
  backend/src/main/java/km/cd/backend/community/domain/Comment.java
  backend/src/main/java/km/cd/backend/community/dto/CommentResponse.java
  backend/src/main/java/km/cd/backend/community/dto/PostResponse.java
  backend/src/main/java/km/cd/backend/community/mapper/CommentMapper.java
  backend/src/main/java/km/cd/backend/community/mapper/PostMapper.java
  backend/src/main/java/km/cd/backend/user/dto/UserResponse.java
  frontend/lib/challenge/complete/challenge_complete_screen.dart
  frontend/lib/challenge/complete/widget/cerification_post_card.dart
  frontend/lib/challenge/create/create_challenge_screen_sec.dart
  frontend/lib/challenge/create/create_challenge_screen_thr.dart
  frontend/lib/challenge/detail/detail_challenge_screen.dart
  frontend/lib/challenge/detail/widgets/certification_method_widget.dart
  frontend/lib/challenge/detail/widgets/detail_widget_information.dart
  frontend/lib/challenge/join/join_challenge_screen.dart
  frontend/lib/challenge/join/join_challenge_screen_sec.dart
  frontend/lib/challenge/search/challenge_search_components.dart
  frontend/lib/challenge/search/challenge_search_screen.dart
  frontend/lib/challenge/state/state_challenge_screen.dart
  frontend/lib/challenge/state/state_screen_widget.dart
  frontend/lib/community/CommunityService.dart
  frontend/lib/community/community_screen.dart
  frontend/lib/community/create_posting_screen.dart
  frontend/lib/community/post_detail_screen.dart
  frontend/lib/community/widget/post_button_widget.dart
  frontend/lib/community/widget/post_card.dart
  frontend/lib/community/widget/post_card_bottom.dart
  frontend/lib/community/widget/post_card_top.dart
  frontend/lib/main.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_challenge_list.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_challenge_recommend_box.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_challenge_state_box.dart
  frontend/lib/main/bottom_tabs/home/home_components/home_top_ChalBox.dart
  frontend/lib/main/bottom_tabs/myRoutineUp/widget/my_routine_up_card.dart
  frontend/lib/main/bottom_tabs/mypage/widget/category_bottom_sheet.dart
  frontend/lib/main/bottom_tabs/mypage/widget/mypage_user_inform.dart
  frontend/lib/main/main_screen.dart
  frontend/lib/model/controller/user_controller.dart
  frontend/lib/model/data/challenge/challenge.dart
  frontend/lib/model/data/challenge/challenge_certification_type.dart
  frontend/lib/model/data/challenge/challenge_simple.dart
  frontend/lib/model/data/challenge/challenge_status.dart
  frontend/lib/model/data/createdPost.dart
  frontend/lib/model/data/post/post.dart
  frontend/lib/model/data/post/post_form.dart
  frontend/lib/model/data/post/simple_post.dart
  frontend/lib/model/data/user.dart
  frontend/lib/model/service/challenge_service.dart
  frontend/lib/model/service/post_service.dart
Labels: 중요도-상, 🍃 백엔드, 💻 프론트엔드, 💡 기능

#161 [be/fix] ChallengeSimpleList를 id 기준 내림차순으로 전송 (#159)
  backend/src/main/java/km/cd/backend/challenge/repository/ChallengeCustomRepositoryImpl.java
Labels: 🍃 백엔드, 🚨 버그

#170 [All] 1일1인증 제한 및 챌린지 현황 페이지 UI
  .idea/.gitignore
  frontend/assets/svgs/certification_disable_btn.svg
  frontend/lib/screens/challenge/create/create_challenge_screen_thr.dart
  frontend/lib/screens/challenge/search/challenge_search_screen.dart
  frontend/lib/screens/challenge/state/state_challenge_screen.dart
  frontend/lib/screens/challenge/state/state_screen_widget.dart
  frontend/lib/screens/main/bottom_tabs/home/home_category_widgets/home_category_component.dart
  frontend/lib/screens/main/bottom_tabs/home/home_components/home_challenge_state_box.dart
  frontend/lib/screens/main/bottom_tabs/home/home_list_widgets/home_challenge_item_card.dart
  frontend/lib/screens/main/bottom_tabs/home/home_list_widgets/home_challenge_list.dart
  frontend/lib/screens/main/bottom_tabs/home/home_list_widgets/home_challenge_recommend_box.dart
  frontend/lib/screens/main/bottom_tabs/home/home_list_widgets/private_code_input_dialog.dart
  frontend/lib/screens/main/bottom_tabs/home/home_screen.dart
  frontend/lib/screens/main/bottom_tabs/home/home_top_box_widgets/home_appBar.dart
  frontend/lib/screens/main/bottom_tabs/home/home_top_box_widgets/home_challenge_state_box.dart
  frontend/lib/screens/main/bottom_tabs/home/home_top_box_widgets/home_state_card.dart
  frontend/lib/screens/main/bottom_tabs/home/home_top_box_widgets/home_top_ChalBox.dart
  frontend/lib/screens/main/bottom_tabs/home/home_top_box_widgets/home_top_stack_box.dart
  frontend/lib/service/post_service.dart
Labels: 중요도-상, 💡 기능

#176 [FE/Fix] #171 #172 #175
  frontend/lib/screens/challenge/create/create_challenge_screen_sec.dart
  frontend/lib/screens/challenge/join/join_challenge_screen_sec.dart
  frontend/lib/screens/challenge/state/state_challenge_screen.dart
  frontend/lib/screens/challenge/state/state_screen_widget.dart
  frontend/lib/screens/community/create_posting_screen.dart
  frontend/lib/screens/main/bottom_tabs/home/home_top_box_widgets/home_state_card.dart
  frontend/lib/screens/main/bottom_tabs/myRoutineUp/widget/my_routine_up_card.dart
Labels: 중요도-상, 💻 프론트엔드, 🚨 버그

#178 [docs] 랜딩 페이지에 맞춰 README 변경
  README.md
  assets/app_logo.png
  assets/architecture.png
  index.md
  media/KakaoTalk_Image_2024-04-01-22-01-59.png
  media/KakaoTalk_Image_2024-04-01-22-02-05.png
  media/KakaoTalk_Photo_2024-04-01-20-17-19.png
  media/readme.md
  media/다운로드.jpeg
  media/스크린샷 2024-04-01 오후 10.08.00.png
  media/스크린샷 2024-04-01 오후 10.24.56.png
  media/팀개인 챌린지.png
Labels: 📑 문서

#179 [AI] 카메라/갤러리 인증 연동 및 UI 수정
  frontend/lib/screens/challenge/certification/camera_view_singleton.dart
  frontend/lib/screens/challenge/certification/certifacation_screen.dart
  frontend/lib/screens/challenge/certification/certification_camera.dart
  frontend/lib/screens/challenge/certification/confirm_image_screen.dart
  frontend/lib/screens/challenge/certification/run_model_by_camera_demo.dart
  frontend/lib/screens/challenge/certification/ui/camera_view.dart
  frontend/lib/screens/challenge/certification/ui/imageConvert.dart
  frontend/lib/screens/challenge/detail/widgets/build_image_container.dart
  frontend/lib/screens/challenge/state/state_screen_widget.dart
  frontend/lib/screens/community/create_posting_screen.dart
  frontend/lib/screens/main/bottom_tabs/home/home_top_box_widgets/home_state_card.dart
  frontend/lib/screens/main/bottom_tabs/myRoutineUp/widget/my_routine_up_card.dart
  frontend/lib/screens/main/bottom_tabs/myRoutineUp/widget/my_routine_widget.dart
Labels: 중요도-상, 💻 프론트엔드

#186 [docs/feat] 앱 스크린샷 추가
  README.md
  assets/app_screenshot.png
Labels: 📑 문서
