Repository kookmin-sw/capstone-2024-31, pull requests merged in 2024-04, with the labels that each got.

#19 [backend/feat]: PrincipalDetails에 user id 추가 및 활용
  backend/src/main/java/km/cd/backend/common/auth/AuthService.java
  backend/src/main/java/km/cd/backend/common/jwt/JwtTokenProvider.java
  backend/src/main/java/km/cd/backend/common/jwt/PrincipalDetails.java
  backend/src/main/java/km/cd/backend/common/oauth2/CustomOAuth2UserService.java
  backend/src/main/java/km/cd/backend/common/oauth2/OAuth2AuthenticationSuccessHandler.java
  backend/src/main/java/km/cd/backend/user/UserController.java
  backend/src/main/java/km/cd/backend/user/UserService.java
  backend/src/main/java/km/cd/backend/user/dto/UserResponse.java
Labels: 🍃 백엔드, 💡 기능

#18 [backend/fix] 500 No static resource 나오는 오류 해결
  backend/src/main/java/km/cd/backend/common/error/CustomExceptionHandler.java
  backend/src/main/resources/application.yml
Labels: ⚙️ 환경설정, 🍃 백엔드, 💡 기능, 🚨 버그

#43 [beackend/feat] S3를 제외한 커뮤니티 기능 구현
  backend/src/main/java/km/cd/backend/BackendApplication.java
  backend/src/main/java/km/cd/backend/common/config/JpaConfig.java
  backend/src/main/java/km/cd/backend/common/domain/BaseTimeEntity.java
  backend/src/main/java/km/cd/backend/community/controller/CommentController.java
  backend/src/main/java/km/cd/backend/community/controller/PostController.java
  backend/src/main/java/km/cd/backend/community/domain/Comment.java
  backend/src/main/java/km/cd/backend/community/domain/Post.java
  backend/src/main/java/km/cd/backend/community/dto/CommentRequest.java
  backend/src/main/java/km/cd/backend/community/dto/CommentResponse.java
  backend/src/main/java/km/cd/backend/community/dto/PostDetailResponse.java
  backend/src/main/java/km/cd/backend/community/dto/PostRequest.java
  backend/src/main/java/km/cd/backend/community/dto/PostSimpleResponse.java
  backend/src/main/java/km/cd/backend/community/mapper/CommentMapper.java
  backend/src/main/java/km/cd/backend/community/mapper/PostMapper.java
  backend/src/main/java/km/cd/backend/community/repository/CommentRepository.java
  backend/src/main/java/km/cd/backend/community/repository/PostRepository.java
  backend/src/main/java/km/cd/backend/community/service/CommentService.java
  backend/src/main/java/km/cd/backend/community/service/PostService.java
  backend/src/test/java/km/cd/backend/community/service/CommentServiceTest.java
  backend/src/test/java/km/cd/backend/community/service/PostServiceTest.java
Labels: 🍃 백엔드, 💡 기능

#44 [backend/feat] 챌린지 생성 기능 수정 / 이미지 저장 로직 구현 / 메시지 전송 기능 구현
  .idea/.gitignore
  .idea/capstone-2024-31.iml
  .idea/compiler.xml
  .idea/gradle.xml
  .idea/jarRepositories.xml
  .idea/misc.xml
  .idea/modules.xml
  .idea/vcs.xml
  backend/build.gradle
  backend/docker-compose-cluster.yml
  backend/src/main/java/km/cd/backend/BackendApplication.java
  backend/src/main/java/km/cd/backend/challenge/controller/ChallengeController.java
  backend/src/main/java/km/cd/backend/challenge/domain/Challenge.java
  backend/src/main/java/km/cd/backend/challenge/domain/ChallengeMapper.java
  backend/src/main/java/km/cd/backend/challenge/domain/Participant.java
  backend/src/main/java/km/cd/backend/challenge/dto/ChallengeReceivedDto.java
  backend/src/main/java/km/cd/backend/challenge/dto/ChallengeResponseDto.java
  backend/src/main/java/km/cd/backend/challenge/dto/enums/ChallengeFrequency.java
  backend/src/main/java/km/cd/backend/challenge/dto/enums/FilePathEnum.java
  backend/src/main/java/km/cd/backend/challenge/service/ChallengeService.java
  backend/src/main/java/km/cd/backend/common/config/S3Config.java
  backend/src/main/java/km/cd/backend/common/config/SecurityConfig.java
  backend/src/main/java/km/cd/backend/common/utils/S3Uploader.java
  backend/src/main/java/km/cd/backend/common/utils/SmsController.java
  backend/src/main/java/km/cd/backend/common/utils/SmsRequestDto.java
  backend/src/main/java/km/cd/backend/common/utils/SmsUtil.java
  backend/src/main/resources/application.yml
Labels: 중요도-중, 🍃 백엔드, 💡 기능

#56 [beackend/feat] 커뮤니티 S3 연동 및 좋아요 기능 추가
  backend/src/main/java/km/cd/backend/challenge/domain/Challenge.java
  backend/src/main/java/km/cd/backend/challenge/dto/enums/FilePathEnum.java
  backend/src/main/java/km/cd/backend/community/controller/CommentController.java
  backend/src/main/java/km/cd/backend/community/controller/PostController.java
  backend/src/main/java/km/cd/backend/community/domain/Like.java
  backend/src/main/java/km/cd/backend/community/domain/Post.java
  backend/src/main/java/km/cd/backend/community/dto/PostDetailResponse.java
  backend/src/main/java/km/cd/backend/community/mapper/PostMapper.java
  backend/src/main/java/km/cd/backend/community/repository/LikeRepository.java
  backend/src/main/java/km/cd/backend/community/service/LikeService.java
  backend/src/main/java/km/cd/backend/community/service/PostService.java
  backend/src/main/java/km/cd/backend/user/UserController.java
  backend/src/test/java/km/cd/backend/community/service/CommentServiceTest.java
  backend/src/test/java/km/cd/backend/community/service/PostServiceTest.java
Labels: 🍃 백엔드, 💡 기능

#58 [beackend/feat] 챌린지 인증 / 현황 기능 구현
  backend/src/main/java/km/cd/backend/challenge/controller/ChallengeController.java
  backend/src/main/java/km/cd/backend/challenge/domain/Challenge.java
  backend/src/main/java/km/cd/backend/challenge/domain/ChallengeMapper.java
  backend/src/main/java/km/cd/backend/challenge/domain/Participant.java
  backend/src/main/java/km/cd/backend/challenge/domain/mapper/ChallengeMapper.java
  backend/src/main/java/km/cd/backend/challenge/dto/CertificationReceivedDto.java
  backend/src/main/java/km/cd/backend/challenge/dto/ChallengeReceivedDto.java
  backend/src/main/java/km/cd/backend/challenge/dto/ChallengeResponseDto.java
  backend/src/main/java/km/cd/backend/challenge/dto/ChallengeStatusResponseDto.java
  backend/src/main/java/km/cd/backend/challenge/dto/enums/ChallengeFrequency.java
  backend/src/main/java/km/cd/backend/challenge/dto/enums/FilePathEnum.java
  backend/src/main/java/km/cd/backend/challenge/repository/ChallengeRepository.java
  backend/src/main/java/km/cd/backend/challenge/repository/ParticipantRepository.java
  backend/src/main/java/km/cd/backend/challenge/scheduler/ChallengeFinishScheduler.java
  backend/src/main/java/km/cd/backend/challenge/service/ChallengeService.java
  backend/src/main/java/km/cd/backend/community/controller/CommentController.java
  backend/src/main/java/km/cd/backend/community/controller/PostController.java
  backend/src/main/java/km/cd/backend/community/repository/PostRepository.java
  backend/src/main/java/km/cd/backend/user/UserController.java
  backend/src/test/java/km/cd/backend/BackendApplicationTests.java
  backend/src/test/java/km/cd/backend/challenge/ChallengeControllerTest.java
  backend/src/test/java/km/cd/backend/challenge/ChallengeServiceTest.java
  backend/src/test/java/km/cd/backend/community/service/PostServiceTest.java
Labels: 중요도-하, 🍃 백엔드, 💡 기능

#65 [feature/backend] 인증 분리
  backend/src/main/java/km/cd/backend/certification/controller/CertificationController.java
  backend/src/main/java/km/cd/backend/certification/domain/Certification.java
  backend/src/main/java/km/cd/backend/certification/domain/CertificationType.java
  backend/src/main/java/km/cd/backend/certification/service/CertificationService.java
  backend/src/main/java/km/cd/backend/challenge/controller/ChallengeController.java
  backend/src/main/java/km/cd/backend/challenge/domain/Challenge.java
  backend/src/main/java/km/cd/backend/challenge/domain/Participant.java
  backend/src/main/java/km/cd/backend/challenge/domain/mapper/ChallengeMapper.java
  backend/src/main/java/km/cd/backend/challenge/dto/CertificationReceivedDto.java
  backend/src/main/java/km/cd/backend/challenge/dto/ChallengeResponseDto.java
  backend/src/main/java/km/cd/backend/challenge/service/ChallengeService.java
  backend/src/main/java/km/cd/backend/community/domain/Post.java
  backend/src/main/java/km/cd/backend/community/repository/PostRepository.java
  backend/src/test/java/km/cd/backend/challenge/ChallengeServiceTest.java
Labels: 🍃 백엔드, 💡 기능

#66 [feature/backend] 전역 예외처리 설정
  backend/src/main/java/km/cd/backend/auth/AuthService.java
  backend/src/main/java/km/cd/backend/challenge/service/ChallengeService.java
  backend/src/main/java/km/cd/backend/common/error/CustomException.java
  backend/src/main/java/km/cd/backend/common/error/CustomExceptionHandler.java
  backend/src/main/java/km/cd/backend/common/error/ErrorResponse.java
  backend/src/main/java/km/cd/backend/common/error/ExceptionCode.java
  backend/src/main/java/km/cd/backend/common/jwt/JwtTokenInvalidException.java
  backend/src/main/java/km/cd/backend/community/service/CommentService.java
  backend/src/main/java/km/cd/backend/community/service/LikeService.java
  backend/src/main/java/km/cd/backend/community/service/PostService.java
  backend/src/main/java/km/cd/backend/user/UserService.java
  backend/src/test/java/km/cd/backend/common/CustomExceptionHandlerTest.java
Labels: 중요도-하, 🍃 백엔드, 💡 기능
